### PR TITLE
fix(pulse-plugin): removed shift max value, added no-chart image (#1559)

### PR DESCRIPTION
**Pull request by dron8552**

### CODE REVIEW

**Comment by tamazlykar** [comment]
run tests

**Comment by dron8552** [comment]
run tests

**Comment by dron8552** [comment]
run tests

**Comment by tamazlykar** [comment]
run tests

**Comment by tamazlykar** [comment]
run tests

**Comment by dron8552** [comment]
run tests

**Comment by dron8552** [comment]
run tests

**Comment by tamazlykar** [comment]
run tests

**Comment by dron8552** [comment]
run tests

**Comment by dron8552** [comment]
run tests

**Comment by dron8552** [comment]
run tests

**Comment by dron8552** [comment]
run tests

**Comment by dron8552** [comment]
run tests

**Comment by dron8552** [comment]
run tests

**Comment by dron8552** [comment]
run tests

**Comment by dron8552** [comment]
run tests

**Pull request merged**
