### PR TITLE
fix(sidebar): doesn't scroll (#1666)

### PR DESCRIPTION
**Pull request by huadream**
Tested: Chromium & Opera & Firefox

### CODE REVIEW

**Comment by bwsw** [comment]
@huadream will review tomorrow.

**Comment by dron8552** [comment]
run tests

**Comment by ershovaelena** [comment]
To test: REQ_GEN_006

**Comment by dron8552** [comment]
run tests

**Comment by dron8552** [comment]
run tests

**Comment by dron8552** [comment]
run tests

**Comment by dron8552** [comment]
run tests

**Pull request merged**
